### ISSUE TITLE
tks~

### ISSUE THREAD

**Issue by moshuying** [betterRunner/context-note#40]
Thanks to your thoughts, the browser first producer goal finally close to completion.
If you have time, we may need to cloud synchronization function, it is easier to implement it in the browser, can be based on such onedrive cloud storage data synchronization to the cloud, such work in the home, when work can continue.

**Comment by betterRunner** [comment]
Thanks for the suggestion. Seems like the data synchronization is a hot demand. I would make a plan to support this feature, not only onedrive but also dropbox, google could and jianguoyun maybe. Please be patient since it might take a while to achieve it. Any update would be posted in this issue.

**Comment by betterRunner** [comment]
@moshuying Hi there, I have checked serval cloud synchronization apps such as [onedrive](https://docs.microsoft.com/en-us/onedrive/developer/controls/file-pickers/js-v72/?view=odsp-graph-online), [dropbox ](https://github.com/dropbox/dropbox-sdk-js)and google could. It seems that it is not easy to integrate them into chrome extension since a lot of restrictions such as CORS and so on need to be solved. I tried them without a success.
Does anyone have experience in this field? A merge request with this feature would be really appreciated.

**Comment by betterRunner** [comment]
Wait a minute, I found the `chrome.storage.sync` function supports sharing data between serval computers with the same google account from [here ](https://stackoverflow.com/questions/4901024/how-to-synchronize-chrome-extension-data-on-different-computers) and I would like to take it a try!

**Comment by moshuying** [comment]
awesome！Thank you for your contribution to this matter. I found some good materials, which may be useful to you。

![image](https://user-images.githubusercontent.com/37231523/150680644-73e04a88-d4b4-4fe5-b325-e07f460b672b.png)

I found the updated documentation and [he is here](https://docs.microsoft.com/zh-cn/microsoft-edge/extensions-chromium/developer-guide/api-support)
[and maybe you need this](https://developer.chrome.com/docs/extensions/reference/storage/#property-sync)

**Comment by betterRunner** [comment]
This feature should be support by `chrome.storage.sync` now, please update to 1.3.7 to take it a try. Thanks for the suggestion and help.
